### ISSUE TITLE
是否叫 regular-ui/base 就可以了？

### ISSUE THREAD

**Issue by leeluolee** [regular-ui/ui-base#1]

**Comment by z-ZYS-s** [comment]
1. 整个库相关的repo前缀为regular-ui-，如regular-ui-bower等
2. 单个组件相关的repo前缀为ui-，如ui-base, ui-dragdrop，类似angular-ui一样
3. 主题相关的repo前缀为theme-，如theme-default, theme-flat
4. 其他的根据情况带前缀或者不带前缀

npm包的命名还是统一用regular-ui-全称的前缀，如regular-ui-base, regular-ui-dragdrop, regular-ui-theme-default，长就长吧，避免冲突。
